// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using STASIS.Data;

#nullable disable

namespace STASIS.Migrations
{
    [DbContext(typeof(StasisDbContext))]
    [Migration("20260303031801_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("STASIS.Models.Approval", b =>
                {
                    b.Property<int>("ApprovalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApprovalID"));

                    b.Property<string>("ApprovalType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EDApprovalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EDApprovalStatus")
                        .HasColumnType("text");

                    b.Property<string>("EDApproverUserId")
                        .HasColumnType("text");

                    b.Property<string>("EDComments")
                        .HasColumnType("text");

                    b.Property<string>("OverallStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("PIApprovalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PIApprovalStatus")
                        .HasColumnType("text");

                    b.Property<string>("PIApproverUserId")
                        .HasColumnType("text");

                    b.Property<string>("PIComments")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RegulatoryApprovalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegulatoryApprovalStatus")
                        .HasColumnType("text");

                    b.Property<string>("RegulatoryApproverUserId")
                        .HasColumnType("text");

                    b.Property<string>("RegulatoryComments")
                        .HasColumnType("text");

                    b.Property<string>("RequestedByUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ApprovalID");

                    b.HasIndex("EDApproverUserId");

                    b.HasIndex("PIApproverUserId");

                    b.HasIndex("RegulatoryApproverUserId");

                    b.HasIndex("RequestedByUserId");

                    b.ToTable("tbl_Approvals", null, t =>
                        {
                            t.HasCheckConstraint("CK_Approvals_ApprovalType", "\"ApprovalType\" IN ('Shipment', 'Discard', 'SingleAliquotException')");

                            t.HasCheckConstraint("CK_Approvals_EDApprovalStatus", "\"EDApprovalStatus\" IS NULL OR \"EDApprovalStatus\" IN ('Pending', 'Approved', 'Rejected')");

                            t.HasCheckConstraint("CK_Approvals_OverallStatus", "\"OverallStatus\" IN ('Pending', 'Approved', 'Rejected')");

                            t.HasCheckConstraint("CK_Approvals_PIApprovalStatus", "\"PIApprovalStatus\" IS NULL OR \"PIApprovalStatus\" IN ('Pending', 'Approved', 'Rejected')");

                            t.HasCheckConstraint("CK_Approvals_RegulatoryApprovalStatus", "\"RegulatoryApprovalStatus\" IS NULL OR \"RegulatoryApprovalStatus\" IN ('Pending', 'Approved', 'Rejected')");
                        });
                });

            modelBuilder.Entity("STASIS.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuditLogID"));

                    b.Property<string>("ChangedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<int>("RecordID")
                        .HasColumnType("integer");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("AuditLogID");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_AuditLog_Timestamp");

                    b.HasIndex("TableName", "RecordID")
                        .HasDatabaseName("IX_AuditLog_TableRecord");

                    b.ToTable("tbl_AuditLog", (string)null);
                });

            modelBuilder.Entity("STASIS.Models.Box", b =>
                {
                    b.Property<int>("BoxID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BoxID"));

                    b.Property<string>("BoxCategory")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Standard");

                    b.Property<string>("BoxLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BoxType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RackID")
                        .HasColumnType("integer");

                    b.HasKey("BoxID");

                    b.HasIndex("BoxLabel")
                        .IsUnique();

                    b.HasIndex("RackID");

                    b.ToTable("tbl_Boxes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Boxes_BoxCategory", "\"BoxCategory\" IN ('Standard', 'Temp', 'Trash', 'Shipping')");

                            t.HasCheckConstraint("CK_Boxes_BoxType", "\"BoxType\" IN ('81-slot', '100-slot', 'Filter Paper Binder')");
                        });
                });

            modelBuilder.Entity("STASIS.Models.FilterPaperUsage", b =>
                {
                    b.Property<int>("FilterPaperUsageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FilterPaperUsageID"));

                    b.Property<bool>("IsInternationalShipment")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("ShipmentContentID")
                        .HasColumnType("integer");

                    b.Property<int>("SpecimenID")
                        .HasColumnType("integer");

                    b.Property<int>("SpotsUsed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UsageDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UsedByUserId")
                        .HasColumnType("text");

                    b.HasKey("FilterPaperUsageID");

                    b.HasIndex("ShipmentContentID");

                    b.HasIndex("SpecimenID");

                    b.HasIndex("UsedByUserId");

                    b.ToTable("tbl_FilterPaperUsages", null, t =>
                        {
                            t.HasCheckConstraint("CK_FilterPaperUsages_SpotsUsed", "\"SpotsUsed\" BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("STASIS.Models.Freezer", b =>
                {
                    b.Property<int>("FreezerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FreezerID"));

                    b.Property<string>("FreezerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocationInBuilding")
                        .HasColumnType("text");

                    b.Property<int?>("Temperature")
                        .HasColumnType("integer");

                    b.HasKey("FreezerID");

                    b.HasIndex("FreezerName")
                        .IsUnique();

                    b.ToTable("tbl_Freezers", (string)null);
                });

            modelBuilder.Entity("STASIS.Models.Rack", b =>
                {
                    b.Property<int>("RackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RackID"));

                    b.Property<int?>("FreezerID")
                        .HasColumnType("integer");

                    b.Property<string>("RackName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RackID");

                    b.HasIndex("FreezerID");

                    b.ToTable("tbl_Racks", (string)null);
                });

            modelBuilder.Entity("STASIS.Models.SampleType", b =>
                {
                    b.Property<int>("SampleTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SampleTypeID"));

                    b.Property<bool>("IsConsumable")
                        .HasColumnType("boolean");

                    b.Property<int?>("LocalReserveUnits")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxShippableUnits")
                        .HasColumnType("integer");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SampleTypeID");

                    b.HasIndex("TypeName")
                        .IsUnique();

                    b.ToTable("tbl_SampleTypes", (string)null);
                });

            modelBuilder.Entity("STASIS.Models.Shipment", b =>
                {
                    b.Property<int>("ShipmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShipmentID"));

                    b.Property<int?>("BatchID")
                        .HasColumnType("integer");

                    b.Property<string>("Courier")
                        .HasColumnType("text");

                    b.Property<string>("DestinationAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsEntireBox")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ShipmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ShippedBoxID")
                        .HasColumnType("integer");

                    b.Property<string>("ShippedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("text");

                    b.HasKey("ShipmentID");

                    b.HasIndex("BatchID");

                    b.HasIndex("ShippedBoxID");

                    b.HasIndex("ShippedByUserId");

                    b.ToTable("tbl_Shipments", (string)null);
                });

            modelBuilder.Entity("STASIS.Models.ShipmentBatch", b =>
                {
                    b.Property<int>("BatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BatchID"));

                    b.Property<int?>("ApprovalID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ImportDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ImportedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("RequestorEmail")
                        .HasColumnType("text");

                    b.Property<string>("RequestorName")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending Approval");

                    b.Property<int>("TotalAvailable")
                        .HasColumnType("integer");

                    b.Property<int>("TotalDiscarded")
                        .HasColumnType("integer");

                    b.Property<int>("TotalNotFound")
                        .HasColumnType("integer");

                    b.Property<int>("TotalNotYetReceived")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPreviouslyShipped")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRequested")
                        .HasColumnType("integer");

                    b.HasKey("BatchID");

                    b.HasIndex("ApprovalID");

                    b.HasIndex("ImportedByUserId");

                    b.ToTable("tbl_ShipmentBatches", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShipmentBatches_Status", "\"Status\" IN ('Pending Approval', 'Approved', 'Rejected', 'Processing', 'Shipped')");
                        });
                });

            modelBuilder.Entity("STASIS.Models.ShipmentContent", b =>
                {
                    b.Property<int>("ShipmentContentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShipmentContentID"));

                    b.Property<string>("ConditionAtShipment")
                        .HasColumnType("text");

                    b.Property<int>("ShipmentID")
                        .HasColumnType("integer");

                    b.Property<string>("ShippingBoxPosition")
                        .HasColumnType("text");

                    b.Property<int>("SpecimenID")
                        .HasColumnType("integer");

                    b.Property<int?>("SpotsUsed")
                        .HasColumnType("integer");

                    b.HasKey("ShipmentContentID");

                    b.HasIndex("ShipmentID");

                    b.HasIndex("SpecimenID");

                    b.ToTable("tbl_ShipmentContents", (string)null);
                });

            modelBuilder.Entity("STASIS.Models.ShipmentRequest", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestID"));

                    b.Property<int?>("BatchID")
                        .HasColumnType("integer");

                    b.Property<int?>("MatchedSpecimenID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedBarcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RequestedSampleTypeID")
                        .HasColumnType("integer");

                    b.Property<string>("RequestorName")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.HasKey("RequestID");

                    b.HasIndex("BatchID");

                    b.HasIndex("MatchedSpecimenID");

                    b.HasIndex("RequestedSampleTypeID");

                    b.ToTable("tbl_ShipmentRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShipmentRequests_Status", "\"Status\" IN ('Pending', 'Staged', 'Shipped', 'Not Found', 'Previously Shipped', 'Discarded', 'Not Yet Received')");
                        });
                });

            modelBuilder.Entity("STASIS.Models.Specimen", b =>
                {
                    b.Property<int>("SpecimenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpecimenID"));

                    b.Property<int?>("AliquotNumber")
                        .HasColumnType("integer");

                    b.Property<string>("BarcodeID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("BoxID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CollectionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DiscardApprovalID")
                        .HasColumnType("integer");

                    b.Property<string>("LegacyID")
                        .HasColumnType("text");

                    b.Property<int?>("PositionCol")
                        .HasColumnType("integer");

                    b.Property<int?>("PositionRow")
                        .HasColumnType("integer");

                    b.Property<int?>("RemainingSpots")
                        .HasColumnType("integer");

                    b.Property<int?>("SampleTypeID")
                        .HasColumnType("integer");

                    b.Property<int>("SpotsReservedLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("SpotsShippedInternational")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("In-Stock");

                    b.Property<int?>("StudyID")
                        .HasColumnType("integer");

                    b.HasKey("SpecimenID");

                    b.HasIndex("BarcodeID")
                        .IsUnique();

                    b.HasIndex("DiscardApprovalID");

                    b.HasIndex("SampleTypeID");

                    b.HasIndex("StudyID");

                    b.HasIndex("BoxID", "PositionRow", "PositionCol")
                        .IsUnique();

                    b.ToTable("tbl_Specimens", null, t =>
                        {
                            t.HasCheckConstraint("CK_Specimens_AliquotNumber", "\"AliquotNumber\" IS NULL OR \"AliquotNumber\" IN (1, 2)");

                            t.HasCheckConstraint("CK_Specimens_Status", "\"Status\" IN ('In-Stock', 'Staged', 'Shipped', 'Missing', 'Depleted', 'Discarded', 'Temp', 'Not Yet Received')");
                        });
                });

            modelBuilder.Entity("STASIS.Models.Study", b =>
                {
                    b.Property<int>("StudyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudyID"));

                    b.Property<string>("PrincipalInvestigator")
                        .HasColumnType("text");

                    b.Property<string>("StudyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudyName")
                        .HasColumnType("text");

                    b.HasKey("StudyID");

                    b.HasIndex("StudyCode")
                        .IsUnique();

                    b.ToTable("tbl_Studies", (string)null);
                });

            modelBuilder.Entity("STASIS.Models.UserProfile", b =>
                {
                    b.Property<int>("UserProfileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserProfileID"));

                    b.Property<string>("AspNetUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CanApproveDiscards")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanApproveShipments")
                        .HasColumnType("boolean");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.HasKey("UserProfileID");

                    b.HasIndex("AspNetUserId")
                        .IsUnique();

                    b.ToTable("tbl_UserProfiles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("STASIS.Models.Approval", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "EDApproverUser")
                        .WithMany()
                        .HasForeignKey("EDApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "PIApproverUser")
                        .WithMany()
                        .HasForeignKey("PIApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "RegulatoryApproverUser")
                        .WithMany()
                        .HasForeignKey("RegulatoryApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EDApproverUser");

                    b.Navigation("PIApproverUser");

                    b.Navigation("RegulatoryApproverUser");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("STASIS.Models.AuditLog", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("STASIS.Models.Box", b =>
                {
                    b.HasOne("STASIS.Models.Rack", "Rack")
                        .WithMany("Boxes")
                        .HasForeignKey("RackID");

                    b.Navigation("Rack");
                });

            modelBuilder.Entity("STASIS.Models.FilterPaperUsage", b =>
                {
                    b.HasOne("STASIS.Models.ShipmentContent", "ShipmentContent")
                        .WithMany()
                        .HasForeignKey("ShipmentContentID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("STASIS.Models.Specimen", "Specimen")
                        .WithMany("FilterPaperUsages")
                        .HasForeignKey("SpecimenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "UsedByUser")
                        .WithMany()
                        .HasForeignKey("UsedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ShipmentContent");

                    b.Navigation("Specimen");

                    b.Navigation("UsedByUser");
                });

            modelBuilder.Entity("STASIS.Models.Rack", b =>
                {
                    b.HasOne("STASIS.Models.Freezer", "Freezer")
                        .WithMany("Racks")
                        .HasForeignKey("FreezerID");

                    b.Navigation("Freezer");
                });

            modelBuilder.Entity("STASIS.Models.Shipment", b =>
                {
                    b.HasOne("STASIS.Models.ShipmentBatch", "Batch")
                        .WithMany("Shipments")
                        .HasForeignKey("BatchID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("STASIS.Models.Box", "ShippedBox")
                        .WithMany("Shipments")
                        .HasForeignKey("ShippedBoxID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "ShippedByUser")
                        .WithMany()
                        .HasForeignKey("ShippedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Batch");

                    b.Navigation("ShippedBox");

                    b.Navigation("ShippedByUser");
                });

            modelBuilder.Entity("STASIS.Models.ShipmentBatch", b =>
                {
                    b.HasOne("STASIS.Models.Approval", "Approval")
                        .WithMany("ShipmentBatches")
                        .HasForeignKey("ApprovalID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "ImportedByUser")
                        .WithMany()
                        .HasForeignKey("ImportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Approval");

                    b.Navigation("ImportedByUser");
                });

            modelBuilder.Entity("STASIS.Models.ShipmentContent", b =>
                {
                    b.HasOne("STASIS.Models.Shipment", "Shipment")
                        .WithMany("ShipmentContents")
                        .HasForeignKey("ShipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STASIS.Models.Specimen", "Specimen")
                        .WithMany("ShipmentContents")
                        .HasForeignKey("SpecimenID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shipment");

                    b.Navigation("Specimen");
                });

            modelBuilder.Entity("STASIS.Models.ShipmentRequest", b =>
                {
                    b.HasOne("STASIS.Models.ShipmentBatch", "Batch")
                        .WithMany("ShipmentRequests")
                        .HasForeignKey("BatchID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("STASIS.Models.Specimen", "MatchedSpecimen")
                        .WithMany("ShipmentRequests")
                        .HasForeignKey("MatchedSpecimenID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("STASIS.Models.SampleType", "RequestedSampleType")
                        .WithMany("ShipmentRequests")
                        .HasForeignKey("RequestedSampleTypeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Batch");

                    b.Navigation("MatchedSpecimen");

                    b.Navigation("RequestedSampleType");
                });

            modelBuilder.Entity("STASIS.Models.Specimen", b =>
                {
                    b.HasOne("STASIS.Models.Box", "Box")
                        .WithMany("Specimens")
                        .HasForeignKey("BoxID");

                    b.HasOne("STASIS.Models.Approval", "DiscardApproval")
                        .WithMany("DiscardedSpecimens")
                        .HasForeignKey("DiscardApprovalID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("STASIS.Models.SampleType", "SampleType")
                        .WithMany("Specimens")
                        .HasForeignKey("SampleTypeID");

                    b.HasOne("STASIS.Models.Study", "Study")
                        .WithMany("Specimens")
                        .HasForeignKey("StudyID");

                    b.Navigation("Box");

                    b.Navigation("DiscardApproval");

                    b.Navigation("SampleType");

                    b.Navigation("Study");
                });

            modelBuilder.Entity("STASIS.Models.UserProfile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("AspNetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("STASIS.Models.Approval", b =>
                {
                    b.Navigation("DiscardedSpecimens");

                    b.Navigation("ShipmentBatches");
                });

            modelBuilder.Entity("STASIS.Models.Box", b =>
                {
                    b.Navigation("Shipments");

                    b.Navigation("Specimens");
                });

            modelBuilder.Entity("STASIS.Models.Freezer", b =>
                {
                    b.Navigation("Racks");
                });

            modelBuilder.Entity("STASIS.Models.Rack", b =>
                {
                    b.Navigation("Boxes");
                });

            modelBuilder.Entity("STASIS.Models.SampleType", b =>
                {
                    b.Navigation("ShipmentRequests");

                    b.Navigation("Specimens");
                });

            modelBuilder.Entity("STASIS.Models.Shipment", b =>
                {
                    b.Navigation("ShipmentContents");
                });

            modelBuilder.Entity("STASIS.Models.ShipmentBatch", b =>
                {
                    b.Navigation("ShipmentRequests");

                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("STASIS.Models.Specimen", b =>
                {
                    b.Navigation("FilterPaperUsages");

                    b.Navigation("ShipmentContents");

                    b.Navigation("ShipmentRequests");
                });

            modelBuilder.Entity("STASIS.Models.Study", b =>
                {
                    b.Navigation("Specimens");
                });
#pragma warning restore 612, 618
        }
    }
}
